Document test database setup
If your development host is not configured to allow you to connect as
user ``postgres`` without a password, you'll get this exception:

    OperationalError: fe_sendauth: no password supplied

This is not an issue on Travis because it allows connecting without a
password.